#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.31f1_bd5abf232a62"
#define UNITY_VERSION_FULL_NICE "2019.4.31f1 (bd5abf232a62)"
#define UNITY_VERSION_BLD 12409535
#define UNITY_VERSION_DATE 1632818004
#define UNITY_VERSION_WIN "2019.4.31.12409535"
#define UNITY_VERSION_BRANCH "2019.4/staging"
